### ISSUE TITLE
Token authentication fails

### ISSUE THREAD

**Issue by vicerious001** [FoxxMD/deploy-ntfy-alerter#2]
When I set up the ntfy-alerter container with these env vars:
```
NTFY_URL=https://<redacted>
NTFY_TOPIC=<redacted>
NTFY_TOKEN=<redacted>
```
when an alert is triggered, ntfy-alerter logs a 403 (Forbidden) error. If I add NTFY_USER And NTFY_PASSWORD vars, pushes to ntfy work fine. I've confirmed with `curl` that this token is valid and works with my ntfy instance using both the `Authorization` header and empty username with token as password (as described [here](https://docs.ntfy.sh/publish/#access-tokens))

**Comment by Thorazine361** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by FoxxMD** [comment]
Thanks for the bug report. This should now be fixed in the newest `latest` docker image.

**Comment by vicerious001** [comment]
Thanks for the fast turnaround. I've confirmed is working using only the token.
